### ISSUE TITLE
Audio buttons - Razer Ornata Chroma V2

### ISSUE THREAD

**Issue by FIvanO** [openrazer/openrazer#1398]
### Device
Razer Ornata Chroma V2

### Problem
1. Audio buttons (switching songs and play/pause) and scroll (volume) don't work. Scroll works like a mouse scroll, but not a volume scroll.

2. In "razercommander" app, if we select a custom lighting mode the audio buttons and scroll don`t recognize (see image). The app shows that there located a logo (selected with a red backlight on the image) instead. If I use other backlight options - all buttons are backlight well.
![image](https://user-images.githubusercontent.com/23000810/104453564-4d543700-55ad-11eb-9135-f4e85a6f4bdf.png)

I assume, that these problems are connected.

Before installing drivers all buttons were working just fine.

Thanks!

**Comment by lucallero** [comment]
I have exactly the same situation. Also, "fn + pause",  the Sleep function stopped working after installing the driver.

**Comment by blastermaster77** [comment]
I installed the driver too and now the volume scroll and audio buttons do not work. And like @FIvanO comented it did work before the installation of the driver. keep the good work!

**Comment by christophehenry** [comment]
Ok, so here are some inputs about this problem. By reading the code, it appears to me that the audio buttons are handled by the [`razer_raw_event` function](https://github.com/openrazer/openrazer/blob/master/driver/razerkbd_driver.c#L2137). By using a few `printk` functions around, I was able to determine this: the `size` argument of this function has a value of `22` when triggered by media buttons and `fn + ` combination. Not `16`, as filtered by [this line](https://github.com/openrazer/openrazer/blob/master/driver/razerkbd_driver.c#L2149). So, this *should* explain why media button stop working when installing the OpenRazer driver.

**But**

After modifying the driver to debug it and installing it on my system, I noticed 2 things: 
1. the media buttons immediatly started working again (and the system was using the driver because I could see the `printk` statements on `dmesg`)
2. the Polychromatic controller immediately stopped working (crashing with core dumped)
3. the daemon is still working but I can see a critical log:

```
Could not access /sys/devices/pci0000:00/0000:00:14.0/usb1/1-5/1-5:1.2/0003:1532:025D.0004/device_type, file is not owned by plugdev
```

`1532:025D` corresponds to Ornata chroma V2's code. This may be related to the polychromatic crash (maybe Polychromatic is trying to set the light color and brightness on the keyboard via the daemon and the daemon returns an unexpected value)?

Anyway, the fact that the media button start working again when I remove the old driver and install my own version is disturbing. I'd like to dig deeper but I want the inputs of a more experienced developer here.

**Comment by z3ntu** [comment]
This sounds like what's being fixed by #1363, could you try that if that changes anything?

**Comment by christophehenry** [comment]
Sadly, that doesn't change anything. And I feel the problem is far worse on the Ornata V2. Here are the key code I get (`data[0]`) when I debug:

- media buttons (play/pause, next, previous, volume up/down, mute): 2,
- fn button alone: 4 (enters the code block),
- fn + F11/F12: 5.

I may be wrong but this is totally new, right?

**Comment by FIvanO** [comment]
By the way, fn + F11/F12 (backlight intensity), fn + F10 (game mode) doesn't work either

**Comment by zekromisblack** [comment]
I also have been having the same issue but with the razer cynosa v2

**Comment by CarrotNL** [comment]
I can confirm. Same problem here. (razer ornata v2)

**Comment by christophehenry** [comment]
For those having the problem, in the meantime, a wrokaround consists of turning off the daemon (`systemctl stop --user openrazer-daemon.service`) once the system is up. You can bring it back up if you need to customise something using e.g. Polychromatic but, for now, using the daemon breaks the media keys so it's useless beyond keyboard color init on boot.

*Edit:* if ou're using Plychromatic as well, you should shut it down before turning off the daemon as well otherwise it will restart the daemon.

**Comment by johnafogarty4** [comment]
Stopping the daemon seems to make my keyboard pretty angry in general.  It could just be a symptom of arch itself that is struggling.

In either case, hopefully we can get a fix soon, because it's pretty annoying to not have audio control.

**Comment by christophehenry** [comment]
@johnafogarty4 Do you also have Polychromatic installed? It tries to restart the daemon as soon as it detects the daemon is stopped. So you should stop it too. I forgot to mention it in my explaination, I will add it.

*Edit:* I also noticed a strange bug when you stop the daemon where the console will not stop printing newlines after the `systemctl stop --user openrazer-daemon.service`. This can be stopped by just `Ctrl + c`.

**Comment by johnafogarty4** [comment]
@christophehenry - I'm using razer genie, but I will check on closing it to see if that helps.

I 100% experienced the newlines until Ctrl + c.

Thanks.

**Comment by AtlasC0R3** [comment]
Can confirm this is still happening over here too: Parrot OS (or debian), openrazer-daemon 3.0.1, Polychromatic 0.6.0, edge builds. Doesn't seem to be client-applet-controller-thing related.
On a Razer Ornata V2, previous, play/pause and skip input "bcd" in a text editor. Fn+Previous outputs fhjkl, Fn+Play/Pause outputs hjkl and Fn+Skip outputs efhjkl. And of course, volume scroll acts like a mouse scroll wheel.

Sometimes when launching openrazer, everything works just fine, other times it doesn't work and does these bugs. I dunno. I've also had this issue where pressing previous or skip would act like it's double pressing the key being pressed, when openrazer isn't launched.

**Comment by wojciechkaleb** [comment]
I have similar issue with my setup. RazerGenie on Manjaro. I added workaround mentioned by @christophehenry (stoping `systemctl`) However, my keyboard getting wild :| Sometimes it lags and doesn't type character, then it lag and keeps typing next tttttttttttttttttttttttttttttttttttter (that's funny, I didn't want to post a example, but my keyboard wanted to express itself). Sometimes it works ok.

**Comment by anoinoz** [comment]
thanks @christophehenry . 
"systemctl stop --user openrazer-daemon.service" gave me back my multimedia keys ( Ornata V2 ) .

**Comment by SrS2225a** [comment]
Is anyone still having this issue? I am having the same thing happen to me. Just did not know if there is some kind of patch now to fix this, since this github issue been open close to a year now. It is a bit annoying having to start/stop the service whenever I want to change something to the keyboard and then use the normal media keys.

On a sidenote, I also noticed this issue seems to affect the DeathAdder somewhat

**Comment by FIvanO** [comment]
@SrS2225a, yes, I still have
Now I'm just using fn + f5/f6/f7 for switching tracks and play/pause

**Comment by AtlasC0R3** [comment]
Can confirm I still have this issue on Arch Linux and what seems to be the latest release.


> Now I'm just using fn + f5/f6/f7 for switching tracks and play/pause
> 
I've actually never tried that somehow. Although it's a shame that the literal keys that are meant to control music are instead just keys that write "bcd" and a glorified scroll wheel.

**Comment by Bart97** [comment]
Same here. The scroll wheel now sends the correct volume up/down commands, but pressing it will output "bcd". The same happens with other media keys.

**Comment by SamantazFox** [comment]
I have an "Ornata v2" (apparently name changed in v3.1.0) and have the same problem, as posted here: https://github.com/openrazer/openrazer/issues/1552#issuecomment-961211873.

It seems that setting the keyboard back to "device mode" during init fixes the problem:
```diff
--- a/daemon/openrazer_daemon/hardware/keyboards.py
+++ b/daemon/openrazer_daemon/hardware/keyboards.py
@@ -652,6 +652,11 @@
                'set_ripple_effect', 'set_ripple_effect_random_colour']
     DEVICE_IMAGE = "https://assets.razerzone.com/eeimages/support/products/1672/ornata-v2.png"
 
+    def __init__(self, *args, **kwargs):
+        super().__init__(*args, **kwargs)
+
+        self.logger.info('Set back to device mode (Fix for #1398 and/or #1552)')
+        self.set_device_mode(0x00, 0x00)  # Device mode

 class RazerHuntsmanElite(_RippleKeyboard):
     """
```

**Comment by SrS2225a** [comment]
> I have an "Ornata v2" (apparently name changed in v3.1.0) and have the same problem, as posted here: [#1552 (comment)](https://github.com/openrazer/openrazer/issues/1552#issuecomment-961211873).
> 
> It seems that setting the keyboard back to "device mode" during init fixes the problem:
> 
> ```diff
> --- a/daemon/openrazer_daemon/hardware/keyboards.py
> +++ b/daemon/openrazer_daemon/hardware/keyboards.py
> @@ -652,6 +652,11 @@
>                 'set_ripple_effect', 'set_ripple_effect_random_colour']
>      DEVICE_IMAGE = "https://assets.razerzone.com/eeimages/support/products/1672/ornata-v2.png"
>  
> +    def __init__(self, *args, **kwargs):
> +        super().__init__(*args, **kwargs)
> +
> +        self.logger.info('Set back to device mode (Fix for #1398 and/or #1552)')
> +        self.set_device_mode(0x00, 0x00)  # Device mode
> 
>  class RazerHuntsmanElite(_RippleKeyboard):
>      """
> ```

I actually have the Ornata v2 as well. Thank you, I will make those changes and recompile it and see if that helps.

On a side note, the numpad "5" key works as a play/pause button for some reason and does not enter "5" as it should, I have to use the keys on the top, and I am not entirely sure what could be causing it. Luckily all other keys work as you would expect. Maybe the recompile will help with that as well? Ill try it.

**Comment by SamantazFox** [comment]
> I actually have the Ornata v2 as well. Thank you, I will make those changes and recompile it and see if that helps.

You don't need to recompile anything, btw. I've only modified the python daemon. You can directly edit `/usr/lib/python3.9/site-packages/openrazer_daemon/hardware/keyboards.py` (adapt path depending on your distro) with super-user privileges :)

**Comment by AtlasC0R3** [comment]
Thanks @SamantazFox, works perfectly on my end!

**Comment by madalee-com** [comment]
That patch worked fine for me as well on the Ornata v2.  If I turn the patch in to a PR, is it likely to get accepted in it's current form?  This feels like it might be a bit hacky, but I don't know the code well enough to say if it's a good idea to commit it to the master or not.

**Comment by notdido** [comment]
> > I actually have the Ornata v2 as well. Thank you, I will make those changes and recompile it and see if that helps.
> 
> You don't need to recompile anything, btw. I've only modified the python daemon. You can directly edit `/usr/lib/python3.9/site-packages/openrazer_daemon/hardware/keyboards.py` (adapt path depending on your distro) with super-user privileges :)

Editing the file like suggested thorws me an error 
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/daemonize.py", line 245, in start
    self.action(*privileged_action_result)
  File "/usr/bin/openrazer-daemon", line 140, in run_daemon
    daemon = RazerDaemon(verbose=args.verbose,
  File "/usr/lib/python3/dist-packages/openrazer_daemon/daemon.py", line 109, in __init__
    self._device_classes = openrazer_daemon.hardware.get_device_classes()
  File "/usr/lib/python3/dist-packages/openrazer_daemon/hardware/__init__.py", line 24, in get_device_classes
    imported_module = __import__(hw_module, globals=globals(), locals=locals(), fromlist=['*'], level=0)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/hardware/keyboards.py", line 693
    super().__init__(*args, **kwargs)
    ^
IndentationError: expected an indented block

Stopping daemon.
```
Am I doing something wrong?

**Comment by AtlasC0R3** [comment]
> Editing the file like suggested thorws me an error 
> ```Traceback (most recent call last):
> File "/usr/lib/python3/dist-packages/openrazer_daemon/hardware/keyboards.py", line 693
> super().**init**(*args, **kwargs)
> ^ IndentationError: expected an indented block
> ```
> 
> Stopping daemon.
> 
> Am I doing something wrong?

Python is very picky about how you indent code; it seems like you haven't put any spaces before that line of code.
8 spaces *should* be enough to keep Python happy, like so:
![Peek 2022-01-30 15-24](https://user-images.githubusercontent.com/39468657/151716426-7af365e7-4f5c-4f09-8c02-573d9225e50c.gif)

**Comment by notdido** [comment]
That works, thanks man, glad to have my media buttons with polychromatic running.

**Comment by ItsRogueRen** [comment]
Wait, so I'm confused. There IS a solution to this? Do I copy/paste that code to line 693 and I'm done? Or do I have to
 uninstall everything and recompile the daemon?

**Comment by notdido** [comment]
Yes, you dont need to recompile the daemon

**Comment by muesli** [comment]
Can confirm this also happens on the BlackWidow v3 Pro. Workaround applies for this device, too.

**Comment by gardockt** [comment]
With today's v3.3.0 release the bug seems to be fixed for Ornata V2.

**Comment by z3ntu** [comment]
@gardockt You mean for the Ornata (Chroma) V2?

**Comment by z3ntu** [comment]
Probably fixed by #1655 then, closing.

For people experiencing this issue on other devices, please search if for that device an issue is already open and if not, create a new one!

**Comment by ItsRogueRen** [comment]
Still having this issue on the new 3.3.0 version on the Ornata Chroma v2, and I also no longer have the files that was listed earlier to edit? I've completely reinstalled OpenRazer and it installed v3.3.0 so the fix should be there but my media keys still give the 3 letters in everything. 

OS: Pop!_OS 21.10
OpenRazer v3.3.0

**Comment by xamindar** [comment]
This is still a problem on version 3.3.0 for the Blackwidow V3 pro.

I still had to manually add the two self. lines to the "Class for the Razer BlackWidow V3 Pro Wired" for this to resolve it.

**Comment by ntorresalberto** [comment]
I'm experiencing this same issue with a Deathstalker v2 Pro TKL in wired mode.
To be clear, with the daemon running, pressing play/pause outputs `bcd`.
After stopping the daemon with `systemctl --user status openrazer-daemon.service`, the media keys work again (worth mentioning that volume up/down works even with the daemon).

Setup:
Fedora 38
openrazer-daemon 3.7.0

**Comment by z3ntu** [comment]
@ntorresalberto Please open a new issue for that device, and don't comment on year old issues that cover a different device. But please link to this one in the new issue you'll open.
