### ISSUE TITLE
Razer Naga Epic Chroma support (003e/003f)

### ISSUE THREAD

**Issue by kived** [openrazer/openrazer#299]
There's some talk about the Naga Epic Chroma mixed in with #59, but it's not the same device (and using the associated branch doesn't work). It does work if treated like a Naga Hex V2 in some ways. DPI can be changed (most important part for me), and while the lighting effects cannot be changed, the brightness controls do work. Logo settings have no effect at all (I don't think the logo glows on this mouse).

https://gist.github.com/kived/086b0ae08a6a9cf7a30f1e068a87ef7e
(I started with the feature_nagachroma_0x0053 branch and rebased off master)

**Comment by z3ntu** [comment]
* Please post the output of
`lsusb -d 1532:003e -v`
and
`ls -lah /dev/input/by-id/`
* Read [this](https://github.com/terrycain/razer-drivers/wiki/Reverse-Engineering-USB-Protocol) because we probably need packet captures.
* Screenshots of all available options on Razer Synapse are needed.
* And lastly, the product & model number of the device for documentation reasons please.

**Comment by kived** [comment]
Here's the output for 003f. This is the dock when using the mouse in wireless mode. The mouse can also be wired directly via USB in which case the id is 003e. There is no difference in the output of lsusb other than the device id.

```
$ lsusb -d 1532:003f -v

Bus 001 Device 003: ID 1532:003f Razer USA, Ltd 
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x003f 
  bcdDevice            2.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           84
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
```

Dock/Wireless (003f):
```
$ ls -lah /dev/input/by-id/
total 0
drwxr-xr-x 2 root root 180 Jun  6 13:38 .
drwxr-xr-x 4 root root 560 Jun  6 13:38 ..
lrwxrwxrwx 1 root root   9 Jun  6 13:09 usb-Logitech_USB_Receiver-event-kbd -> ../event6
lrwxrwxrwx 1 root root   9 Jun  6 13:09 usb-Logitech_USB_Receiver-if01-event-mouse -> ../event7
lrwxrwxrwx 1 root root   9 Jun  6 13:09 usb-Logitech_USB_Receiver-if01-mouse -> ../mouse1
lrwxrwxrwx 1 root root  10 Jun  6 13:38 usb-Razer_Razer_Naga_Epic_Chroma_Dock-event-mouse -> ../event15
lrwxrwxrwx 1 root root   9 Jun  6 13:38 usb-Razer_Razer_Naga_Epic_Chroma_Dock-if01-event-kbd -> ../event5
lrwxrwxrwx 1 root root   9 Jun  6 13:38 usb-Razer_Razer_Naga_Epic_Chroma_Dock-if02-event-kbd -> ../event8
lrwxrwxrwx 1 root root   9 Jun  6 13:38 usb-Razer_Razer_Naga_Epic_Chroma_Dock-mouse -> ../mouse0
```

Direct USB (003e):
```
$ ls -lah /dev/input/by-id/
total 0
drwxr-xr-x 2 root root 180 Jun  6 13:42 .
drwxr-xr-x 4 root root 560 Jun  6 13:42 ..
lrwxrwxrwx 1 root root   9 Jun  6 13:09 usb-Logitech_USB_Receiver-event-kbd -> ../event6
lrwxrwxrwx 1 root root   9 Jun  6 13:09 usb-Logitech_USB_Receiver-if01-event-mouse -> ../event7
lrwxrwxrwx 1 root root   9 Jun  6 13:09 usb-Logitech_USB_Receiver-if01-mouse -> ../mouse1
lrwxrwxrwx 1 root root  10 Jun  6 13:42 usb-Razer_Razer_Naga_Epic_Chroma-event-mouse -> ../event15
lrwxrwxrwx 1 root root   9 Jun  6 13:42 usb-Razer_Razer_Naga_Epic_Chroma-if01-event-kbd -> ../event8
lrwxrwxrwx 1 root root   9 Jun  6 13:42 usb-Razer_Razer_Naga_Epic_Chroma-if02-event-kbd -> ../event5
lrwxrwxrwx 1 root root   9 Jun  6 13:42 usb-Razer_Razer_Naga_Epic_Chroma-mouse -> ../mouse0
```

Model No: RC30-012301 (Dock: RC30-012302)
Product No: RZ01-01230100

**Comment by kived** [comment]
![screenshot from 2017-06-06 14-42-08](https://user-images.githubusercontent.com/1126441/26853522-39abd478-4ac7-11e7-8105-117edb7d12f1.png)
![screenshot from 2017-06-06 14-42-25](https://user-images.githubusercontent.com/1126441/26853526-3e085bcc-4ac7-11e7-91cd-69762a13480b.png)
![screenshot from 2017-06-06 14-43-02](https://user-images.githubusercontent.com/1126441/26853549-564ab0a4-4ac7-11e7-8c8d-2baa198707bb.png)
![screenshot from 2017-06-06 14-43-45](https://user-images.githubusercontent.com/1126441/26853554-5b35a060-4ac7-11e7-9b99-4ffb5e4bc4b4.png)
![screenshot from 2017-06-06 14-48-21](https://user-images.githubusercontent.com/1126441/26853561-61229ac8-4ac7-11e7-87e8-a5769376e425.png)
![screenshot from 2017-06-06 14-44-03](https://user-images.githubusercontent.com/1126441/26853563-631455ba-4ac7-11e7-9a15-783cc552d487.png)
![screenshot from 2017-06-06 14-44-34](https://user-images.githubusercontent.com/1126441/26853567-648a10a6-4ac7-11e7-917f-c79878240831.png)

**Comment by terricain** [comment]
Need captures: (repeat for wired and wireless)
* 1 capture of slide dpi from min to max to min
* 1 capture of poll rate from 125, 250, 500
* a capture of each and every lighting option
* 1 capture of brightness off, dim, normal bright
* 1 capture of sleep mode idel min to max to min
* 1 capture of blink when low power min to max to min
* 1 capture of leaving the mouse not moving for ~10 min

**Comment by drewhoener** [comment]
Any progress on this / anything I can do to help speed this along? It'd be nice to be able to configure my epic :)

**Comment by terricain** [comment]
^^

**Comment by Fyro-Ing** [comment]
could you explain me how to take this capture ? 

with wireshark ? other ?

**Comment by z3ntu** [comment]
https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol

**Comment by Fyro-Ing** [comment]
i've installed virtualbox, but mouse is not recognized as a Razer mouse.
is there a specific configuration to do this ?

**Comment by z3ntu** [comment]
@Fyro-Ing Did you pass through the USB device to the VM? And please be aware that the mouse is then exclusively available for the VM as long as it's running so I recommend plugging in a second mouse to use for the "outside OS"/host.

**Comment by Fyro-Ing** [comment]
all is good now with the [virtualbox documentation](https://forums.virtualbox.org/viewtopic.php?f=35&t=82639) (my problems : not in virtualbox user group and a virtualbox distro (not sure -- no try with only group user -- for that but in the doubt ^^ ) => no device)

now, i go to see samples on other issues to do the job correctly, i hope the next week, thanks

**Comment by nyejyh** [comment]
I would like to contribute as I have this mouse too.  I understand we need the captures as @terrycain was asking for earlier.  Currently I'm stuck figuring out what channel I need to look at on Wireshark.  I already have the information such as Bus/Device numbers and applied the filters accordingly:
```
**Razer Naga Epic Chroma (Wired Mode)**
$ lsusb
Bus 003 Device 010: ID 1532:003e Razer USA, Ltd

**Razer Naga Epic Chroma (Wireless Mode)**
$ lsusb
Bus 003 Device 009: ID 1532:003f Razer USA, Ltd
```
```
**Razer Naga Epic Chroma (Wired Mode)**
Filter: usb.bus_id == 3 && usb.device_address == 10

**Razer Naga Epic Chroma (Wireless Mode)**
Filter: usb.bus_id == 3 && usb.device_address == 9
```
Please see what channels I have so far on Wireshark.  Which channel should I focus on?
![image](https://user-images.githubusercontent.com/12264508/35017916-06070f76-fad4-11e7-86be-30a8958069c2.png)

**Comment by lvlupblumana** [comment]
I have a zip file of the Razer Naga Epic Chroma captures in both wired and wireless modes as requested by @terrycain in earlier post.  Please note that the poll rate for this mouse is actually 125, 500, 1000.
[Razer Naga Epic Chroma Captures.zip](https://github.com/openrazer/openrazer/files/1638176/Razer.Naga.Epic.Chroma.Captures.zip)

**Comment by lvlupblumana** [comment]
Any updates?  I can retake captures if needed.

**Comment by z3ntu** [comment]
No, I don't think yours are good (and recognized by our scripts). I am just currently very busy learning PL/SQL 😉 (until tomorrow)

**Comment by lvlupblumana** [comment]
Thanks for letting me know! :smile:  What can I do to make sure the captures are good and recognized by your scripts?  Do I need to throw the data into the colorizer?  I was following another example of posting the captures in which they were accepted, but maybe I did something wrong.

Also, good luck on your learning, it sounds like a lot of fun! :+1:

**Comment by z3ntu** [comment]
"Fun".
I think it's getting recognized (@terrycain wrote the scripts btw) because it uses an older version of the protocol which is known by the scripts.

**Comment by z3ntu** [comment]
I've pushed a commit making the first steps to being supported d35f8259514c13693ca04ffe0653ba3b6220302a
It compiles but needs more changes to work properly.

**Comment by lvlupblumana** [comment]
I can't tell you how happy I am to hear about this! :smile:

**Comment by z3ntu** [comment]
Okay I have a state that might work on the branch `feature_nagaepicchroma_0x003e`. Which distro do you use so I can give you instructions on how to compile the package from that branch?

**Comment by lvlupblumana** [comment]
I used Debian 9 Stretch.

**Comment by z3ntu** [comment]
Then
```
git clone https://github.com/openrazer/openrazer -b feature_nagaepicchroma_0x003e
cd openrazer/
./scripts/build_debs.sh
```
If you get an error, look into the log file that's printed and install the missing build dependencies listed there.
**EDIT:** The script seems to be broken for some reason. I'll look into it.

**Comment by z3ntu** [comment]
I fixed the problem and rebased the `feature_nagaepicchroma_0x003e` branch on master. It's probably easiest if you delete the folder you might have cloned before and run the three commands again.

**Comment by nyejyh** [comment]
Thanks, your fix solved a different issue I was running into.  I am now stuck at the part where I already updated linux-headers-generic to the latest version (4.9.65-3+deb9u2) but the error still throws a "Failed to generate deb files."

**Comment by z3ntu** [comment]
Can you give me the contents of the log file?

**Comment by nyejyh** [comment]
```
nyejyh@BananaHarvester:/tmp$ cat tmp.nmh2cAjHCM_deb_build_tmp/build.log 
dpkg-buildpackage: info: source package openrazer
dpkg-buildpackage: info: source version 2.2.0
dpkg-buildpackage: info: source distribution xenial
dpkg-buildpackage: info: source changed by Luca Weiss <luca@z3ntu.xyz>
 dpkg-source --before-build razer
dpkg-buildpackage: info: host architecture amd64
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
dpkg-checkbuilddeps: error: Unmet build dependencies: linux-headers-generic
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
```

**Comment by z3ntu** [comment]
Run `sed -i '/linux-headers-generic/d' debian/control` and try again. That package is not available on Debian as far as I know.

**Comment by nyejyh** [comment]
Different error now, pasted below:
```
nyejyh@BananaHarvester:/tmp$ cat tmp.MJ91kfcxWY_deb_build_tmp/build.log
dpkg-buildpackage: info: source package openrazer
dpkg-buildpackage: info: source version 2.2.0
dpkg-buildpackage: info: source distribution xenial
dpkg-buildpackage: info: source changed by Luca Weiss <luca@z3ntu.xyz>
 dpkg-source --before-build razer
dpkg-buildpackage: info: host architecture amd64
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
 fakeroot debian/rules clean
dh clean --with-python3
   dh_testdir -O--with-python3
   debian/rules override_dh_auto_clean
make[1]: Entering directory '/tmp/tmp.MJ91kfcxWY_deb_build_tmp/razer'
/usr/bin/make lp_driver_clean
make[2]: Entering directory '/tmp/tmp.MJ91kfcxWY_deb_build_tmp/razer'
-e 
:: Cleaning OpenRazer kernel modules (Launchpad)
========================================
make -C "/lib/modules/4.9.0-5-amd64/build" SUBDIRS="/tmp/tmp.MJ91kfcxWY_deb_build_tmp/razer/driver" clean
make[3]: Entering directory '/usr/src/linux-headers-4.9.0-5-amd64'
make[3]: Leaving directory '/usr/src/linux-headers-4.9.0-5-amd64'
make[2]: Leaving directory '/tmp/tmp.MJ91kfcxWY_deb_build_tmp/razer'
make[1]: Leaving directory '/tmp/tmp.MJ91kfcxWY_deb_build_tmp/razer'
   dh_clean -O--with-python3
 dpkg-source -b razer
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
dpkg-source: error: can't build with source format '3.0 (quilt)': non-native package version does not contain a revision
dpkg-buildpackage: error: dpkg-source -b razer gave error exit status 255
```

**Comment by z3ntu** [comment]
Sorry for that. Building the debs now works in my Debian Testing VM.

**Comment by z3ntu** [comment]
Run the sed command in the git repository. The linux-headers-generic dependency is only valid for Ubuntu and that sed commands removes that dependency

**Comment by nyejyh** [comment]
It works!  Does this mean you can integrate this into Open Razer?
```
nyejyh@BananaHarvester:~/openrazer$ ./scripts/build_debs.sh
Temp DIR: /tmp/tmp.0ghG4twamC_deb_build_tmp
Copying source to temporary build directory
Building deb packages

Deb packages build successfully. Copied to ./dist/
```

**Comment by z3ntu** [comment]
You have to install the deb packages that are in the `dist/` directory (e.g. with `sudo dpkg -i ./dist/*.deb && sudo apt install -f`)

**Comment by Fyro-Ing** [comment]
hello, how to build for ubuntu xenial ?

**Comment by nyejyh** [comment]
Building all the deb packages succeed, however there were some error messages related to dependency problems:
```
nyejyh@BananaHarvester:~/openrazer$ sudo dpkg -i ./dist/*.deb && sudo apt install -f
Selecting previously unselected package openrazer-daemon.
(Reading database ... 163989 files and directories currently installed.)
Preparing to unpack .../openrazer-daemon_2.2.0-1_amd64.deb ...
Unpacking openrazer-daemon (2.2.0-1) ...
Selecting previously unselected package openrazer-doc.
Preparing to unpack .../openrazer-doc_2.2.0-1_all.deb ...
Unpacking openrazer-doc (2.2.0-1) ...
Selecting previously unselected package openrazer-kernel-modules-dkms.
Preparing to unpack .../openrazer-kernel-modules-dkms_2.2.0-1_amd64.deb ...
Unpacking openrazer-kernel-modules-dkms (2.2.0-1) ...
Selecting previously unselected package openrazer-meta.
Preparing to unpack .../openrazer-meta_2.2.0-1_all.deb ...
Unpacking openrazer-meta (2.2.0-1) ...
Selecting previously unselected package python3-openrazer.
Preparing to unpack .../python3-openrazer_2.2.0-1_all.deb ...
Unpacking python3-openrazer (2.2.0-1) ...
dpkg: dependency problems prevent configuration of openrazer-daemon:
 openrazer-daemon depends on python3-pyudev; however:
  Package python3-pyudev is not installed.
 openrazer-daemon depends on python3-evdev; however:
  Package python3-evdev is not installed.
 openrazer-daemon depends on python3-setproctitle; however:
  Package python3-setproctitle is not installed.
 openrazer-daemon depends on python3-notify2; however:
  Package python3-notify2 is not installed.
 openrazer-daemon depends on python3-daemonize; however:
  Package python3-daemonize is not installed.
 openrazer-daemon depends on xautomation; however:
  Package xautomation is not installed.
 openrazer-daemon depends on xdotool; however:
  Package xdotool is not installed.

dpkg: error processing package openrazer-daemon (--install):
 dependency problems - leaving unconfigured
Setting up openrazer-doc (2.2.0-1) ...
Setting up openrazer-kernel-modules-dkms (2.2.0-1) ...
Loading new openrazer-driver-1.0.0 DKMS files...
Building for 4.9.0-5-amd64
Building initial module for 4.9.0-5-amd64
Done.

razerkbd:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.9.0-5-amd64/updates/dkms/

razermouse.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.9.0-5-amd64/updates/dkms/

razerfirefly.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.9.0-5-amd64/updates/dkms/

razerkraken.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.9.0-5-amd64/updates/dkms/

razermug.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.9.0-5-amd64/updates/dkms/

razercore.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.9.0-5-amd64/updates/dkms/

depmod...

DKMS: install completed.
-e 
ADD YOUR USER TO THE PLUGDEV GROUP 'sudo gpasswd -a <USERNAME> plugdev'
dpkg: dependency problems prevent configuration of openrazer-meta:
 openrazer-meta depends on openrazer-daemon; however:
  Package openrazer-daemon is not configured yet.

dpkg: error processing package openrazer-meta (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of python3-openrazer:
 python3-openrazer depends on python3-numpy; however:
  Package python3-numpy is not installed.

dpkg: error processing package python3-openrazer (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.7.6.1-2) ...
Errors were encountered while processing:
 openrazer-daemon
 openrazer-meta
 python3-openrazer
```

**Comment by Fyro-Ing** [comment]
you need to install dependencies : 
python3-pyudev python3-evdev python3-setproctitle python3-notify2 python3-daemonize xautomation xdotool


For ubuntu => ./scripts/build_debs.sh is OK

but daemon start with 2 similar errors : 

*** on session started (same as command line /usr/bin/openrazer-daemon &) : 
  File "/usr/bin/openrazer-daemon", line 178, in <module>
    run()
  File "/usr/bin/openrazer-daemon", line 173, in run
    logger=logger)
TypeError: __init__() got an unexpected keyword argument 'chdir'


*** with command line /usr/bin/openrazer-daemon

Traceback (most recent call last):
  File "/usr/bin/openrazer-daemon", line 178, in <module>
    run()
  File "/usr/bin/openrazer-daemon", line 173, in run
    logger=logger)
TypeError: __init__() got an unexpected keyword argument 'foreground'

**Comment by nyejyh** [comment]
@Fyro-Ing Thanks for pointing that out, my bad.  Installed the packages as you mentioned with no errors.  Is this where I can install applications like Polychromatic to test the drivers?

**Comment by Fyro-Ing** [comment]
After restart computer, yes if openrazer-daemon is running

**Comment by z3ntu** [comment]
Some dependencies are only available in the ppa so adding that should help with these problems.

**Comment by nyejyh** [comment]
Currently testing RazerGenie but running into errors.  Is the stable version of OpenRazer supposed to be installed before all this?

**Comment by z3ntu** [comment]
What issues? And no, you need the 3 or 4 packages built from the support branch as it's not supported in master.

**Comment by nyejyh** [comment]
All the dependencies have been installed without issues, so building deb packages have succeeded.  Currently seeing this when running RazerGenie:
```
● openrazer-daemon.service - Daemon to manage razer devices in userspace
   Loaded: loaded (/usr/lib/systemd/user/openrazer-daemon.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2018-01-23 11:50:30 PST; 24s ago
     Docs: man:openrazer-daemon(8)
  Process: 2353 ExecStart=/usr/bin/openrazer-daemon -Fv (code=exited, status=1/FAILURE)
 Main PID: 2353 (code=exited, status=1/FAILURE)
```

**Comment by z3ntu** [comment]
Run "openrazer-daemon -Fv" in your terminal and check the output. I guess it's that your user is not a member of the plugdev group

**Comment by nyejyh** [comment]
I'm pretty sure I added my user to the group:
```
nyejyh@BananaHarvester:~/openrazer$ history
...
  456  cd openrazer/
  457  sudo dpkg -i ./dist/*.deb && sudo apt install -f
  458  sudo gpasswd -a nyejyh plugdev

```
Here is the output of the command:
```
nyejyh@BananaHarvester:~/openrazer$ openrazer-daemon -Fv
Traceback (most recent call last):
  File "/usr/bin/openrazer-daemon", line 12, in <module>
    from openrazer_daemon.daemon import RazerDaemon, __version__
ModuleNotFoundError: No module named 'openrazer_daemon'
```

**Comment by z3ntu** [comment]
What does `python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`
output and what does `ls -ald /usr/lib/python3/*/openrazer*` print?

**Comment by nyejyh** [comment]
First output:
```
nyejyh@BananaHarvester:~/openrazer$ python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
/home/nyejyh/anaconda3/lib/python3.6/site-packages
```
Second output:
```
nyejyh@BananaHarvester:~/openrazer$ ls -ald /usr/lib/python3/*/openrazer*
drwxr-xr-x 4 root root 4096 Jan 23 11:46 /usr/lib/python3/dist-packages/openrazer
drwxr-xr-x 5 root root 4096 Jan 23 11:46 /usr/lib/python3/dist-packages/openrazer_daemon
```

**Comment by z3ntu** [comment]
Did you install a custom version of python 3? Because the path from the first command should be /usr/lib/python3/dist-packages

**Comment by z3ntu** [comment]
#503 was about another installation that pointed to the home directory for the lib path, maybe you can find something in there.

**Comment by Fyro-Ing** [comment]
@z3ntu any ideas for my problem ? https://github.com/openrazer/openrazer/issues/299#issuecomment-359892093

**Comment by z3ntu** [comment]
@fyro-ing seems you have an old version of python3-daemonize installed. So add the ppa (see our website) and do a system upgrade.

**Comment by Fyro-Ing** [comment]
it's good but razergenie or polychromatic not detect device

if daemon log, seems to be ok 
2018-01-23 22:41:10 | razer                          | DEBUG    | Loaded device specification: RazerNagaEpicChromaWired ---------------- (1532:003E)

**Comment by z3ntu** [comment]
Did you try to reboot?

**Comment by Fyro-Ing** [comment]
yes, but same result

**Comment by nyejyh** [comment]
Attempt to reinstall Python 3 resulted in a fresh copy of Debian 9.  Redid all the steps with successful building of debs.  Below is different error:
```
nyejyh@BananaHarvester:~$ openrazer-daemon -Fv
Traceback (most recent call last):
  File "/usr/bin/openrazer-daemon", line 178, in <module>
    run()
  File "/usr/bin/openrazer-daemon", line 173, in run
    logger=logger)
TypeError: __init__() got an unexpected keyword argument 'foreground'

```

**Comment by z3ntu** [comment]
You can probably follow something similar to https://stackoverflow.com/a/7901603/3527128 (of course with adjusted paths) to achieve this; or you use the path Debian uses for adjusting that path.

**Comment by evaue** [comment]
@z3ntu will this actually compile if I modify the PKGBUILD slightly for openrazer-git so it points to this branch?

**Comment by z3ntu** [comment]
@evaue Yes, that will work (so `source=("$pkgbase::git+https://github.com/openrazer/openrazer.git#branch=feature_nagaepicchroma_0x003e")`)

**Comment by nyejyh** [comment]
Sorry if this is a bit of a noob question.  How do I make the PYTHONPATH work?  I need to have Anaconda's version of Python to work on projects too, so would having both lines not commented in the file still work?  This is what I have in the bashrc:
```
# added by Anaconda2 installer
#export PATH="/home/nyejyh/anaconda2/bin:$PATH"
export PYTHONPATH=$PYTHONPATH:/usr/lib/python3
```
Running a search on what Python I have gave me:
```
nyejyh@BananaHarvester:~$ ls /usr/lib/python*
/usr/lib/python2.7
/usr/lib/python3
/usr/lib/python3.5
```

**Comment by z3ntu** [comment]
I think adding `/usr/lib/python3/dist-packages` is what you want.

**Comment by Fyro-Ing** [comment]
@z3ntu For my problem, this is the razer daemon log https://pastebin.com/8ErjGR08

we see "DBus called get_serial_list" whith polychromatic and razergenie
mouse connected : Bus 003 Device 004: ID 1532:003e Razer USA, Ltd

so i suppose that it's not a device bug

**Comment by z3ntu** [comment]
@Fyro-Ing Run `sudo dkms install openrazer-driver/1.0.0`

**Comment by Fyro-Ing** [comment]
> Module openrazer-driver/1.0.0 already installed on kernel 4.4.0-93-generic/x86_64

**Comment by z3ntu** [comment]
@Fyro-Ing Did you try to reboot? If that didn't help, please join our community chat, either via Telegram (https://t.me/joinchat/A1E4RT9TxhnxyetdQCSj7Q) or via Matrix (https://matrix.to/#/#openrazer:matrix.org). This issue is getting too crowded with random help and it's getting confusing.

**Comment by z3ntu** [comment]
I removed a bunch of support-type comments which are not essential for device support but were general questions which are solved now (mostly at least).

**Comment by 00Asgaroth00** [comment]
I have one of these mice and would be willing to test too, do you still need testers?

**Comment by z3ntu** [comment]
@00Asgaroth00 Which distro do you use?

**Comment by 00Asgaroth00** [comment]
@z3ntu I'm on Ubuntu 17.10 at the moment.

**Comment by z3ntu** [comment]
Then you can do
```
git clone https://github.com/openrazer/openrazer -b feature_nagaepicchroma_0x003e
cd openrazer/
./scripts/build_debs.sh
sudo dpkg -i dist/*.deb
sudo apt install -f
```

**Comment by 00Asgaroth00** [comment]
@z3ntu I already have the stable release of openrazer installed on the system, do I need to uninstall that or can I run this alongside the stable release?

**Comment by z3ntu** [comment]
This will build new .deb files that will replace the existing ones so you don't have to do anything special (you can actually skip the last command if you have it already installed).

**Comment by 00Asgaroth00** [comment]
thanks, I'll give it a shot, is there any specific information you're looking for while in testing phase?

**Comment by z3ntu** [comment]
Basically what works and what doesn't work

**Comment by 00Asgaroth00** [comment]
OK, am getting this error:

```
dpkg-buildpackage: info: source package openrazer
dpkg-buildpackage: info: source version 2.2.2-1
dpkg-buildpackage: info: source distribution xenial
dpkg-buildpackage: info: source changed by Luca Weiss <luca@z3ntu.xyz>
 dpkg-source --before-build razer
dpkg-buildpackage: info: host architecture amd64
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper (>= 8.0.0)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
```
Do I need to install some software build group package, what is it called under ubuntu? (I'm used to centos package groups)

**Comment by z3ntu** [comment]
Just install debhelper (or other packages that show up with the "Unmet build dependencies:") with apt.

**Comment by 00Asgaroth00** [comment]
OK, thanks, packages built and installed now, but I dont see a module loaded for the mouse, can I manually "modprobe" it into action, or do I need to do a full reboot?

```
razerkbd               57344  0
razerkraken            20480  0
hid                   118784  4 hid_generic,usbhid,razerkbd,razerkraken
```

**Comment by z3ntu** [comment]
Either plug the mouse out and back in, run `sudo udevadm trigger` (if this works, please says so^^) or reboot.

**Comment by 00Asgaroth00** [comment]
unplug/pluggin back in the mouse seems to have got the driver loaded:

```
razermouse             65536  0
razerkbd               57344  0
razerkraken            20480  0
hid                   118784  5 razermouse,hid_generic,usbhid,razerkbd,razerkraken
```

I did not run the udev trigger command, do you still want me to do that?

**Comment by z3ntu** [comment]
No. Theoretically that command should have the same effect as replugging the device.

**Comment by nokilli** [comment]
Hi, lurker here.

I've installed this latest patch using Gentoo.  Used the instructions for Gentoo, changing project name from razer-drivers to openrazer and adding the line:
>EGIT_BRANCH="feature_nagaepicchroma_0x003e"

at the top of the ebuild. 

Rebooted, appears to load:
>Apr  8 04:10:43 rage kernel: razermouse 0003:1532:003E.0002: input,hidraw0: USB HID v1.11 Keyboard [Razer Razer Naga Epic Chroma] on usb-0000:00:1d.0-1.2/input1
Apr  8 04:10:43 rage kernel: razermouse 0003:1532:003E.0003: input,hidraw1: USB HID v1.11 Keyboard [Razer Razer Naga Epic Chroma] on usb-0000:00:1d.0-1.2/input2
Apr  8 04:10:43 rage kernel: razermouse 0003:1532:003E.0001: input,hidraw2: USB HID v1.11 Mouse [Razer Razer Naga Epic Chroma] on usb-0000:00:1d.0-1.2/input0

> cat /sys/bus/hid/drivers/razermouse/0003:1532:003E.0001/device_type
Razer Naga Epic Chroma

> cat /sys/bus/hid/drivers/razermouse/0003:1532:003E.0001/device_mode
0:0

The feature I am hoping for however is not working.  This would be where I get different button codes for tilting the scroll wheel than I do by scrolling with the wheel, e.g., scrolling up and tilting right both see xev return:
> ButtonRelease event, serial 25, synthetic NO, window 0x1e00001,
    root 0x4c2, subw 0x1e00002, time 4092911, (27,42), root:(27,42),
    state 0x1000, button 5, same_screen YES

Tried setting device_mode to 3:0 just to be thorough, as documented, it disables the tilt wheel.

Is there anything further I can do to help diagnosis this?

**Comment by HeyZeusV** [comment]
I too have this mouse and would love to help test it! I am currently running Mint 18.3

**Comment by z3ntu** [comment]
@HeyZeusV Please follow https://github.com/openrazer/openrazer/wiki/Building-a-package#ubuntu--linux-mint and replace the `TARGET_BRANCH` with `feature_nagaepicchroma_0x003e`

@00Asgaroth00 Test results from you?

@nokilli Sorry, button remapping (including scrollwheel tilt button) is not supported yet. Pull requests welcome!

**Comment by 00Asgaroth00** [comment]
@z3ntu So far the mouse "works", but, to be honest, I've not tested any of the features yet, what I have noticed though, is the following log messages in the syslog of ubuntu:

```
Apr 12 00:14:03 arakasi kernel: [89616.135088] razer driver: Invalid USB repsonse. USB Report length: -110
Apr 12 00:14:03 arakasi kernel: [89616.135092] razermouse: Invalid Report Length. Start Marker: 00 id: 00 Num Params: 00 Reserved: 00 Command: 00 Params: 00000000000000000000000000000000 .
```
These occur sporadically and I cannot reproduce them. I'm also seeing these messages sporadically, but again, I cannot reproduce, although, I'm not sure if these are directly related to the razermouse driver:

```
Apr 12 06:50:22 arakasi /usr/lib/gdm3/gdm-x-session[7736]: (II) event8  - (II) Razer Razer Naga Epic Chroma: (II) SYN_DROPPED event - some input events have been lost.
```

**Comment by z3ntu** [comment]
These messages are quite normal - Razer devices love to reject messages and send some weird stuff back. For details you have to ask Terry :wink:

**Comment by 00Asgaroth00** [comment]
update:

So far general mouse use works fine, scrolling/left-right click, the buttons on the left 1-12. I have not tried the 2 buttons on top yet.

RazerGenie is able to set the colour stuff. I have not dabbled too much with DPI settings at the moment.

Are we able to map keys to the keys on the left side of the mouse yet (1-12)?

What other features are we looking to test on this mouse?

**Comment by z3ntu** [comment]
Please compile the newest version of RazerGenie (only on git master currently - instructions are in the readme file there) and try again. You should then see "Backlight" lighting options listed in RazerGenie that should change that LED.

Also did you try the mouse in wireless mode?

And no sorry, key remapping is not yet supported. You might be able to use other applications for that though.

**Comment by tallsam** [comment]
Hi, just gave this branch a go and it looks pretty good. DPI works. scroll wheel static and spectrum work. theres nothing under backlight, but maybe that is different to the colors on the side buttons.

Let me know if theres any other info you would like.

**Comment by tallsam** [comment]
I keep getting notifications saying that the battery is at 100%, and i'm running wired. So that seems a bit superfluous. I disabled it in the config (~/.config/openrazer/razer.conf), but perhaps it should be detecting if we are running wired or on battery.

**Comment by z3ntu** [comment]
@tallsam You should see these options in RazerGenie if you compiled it from the newest source: 
![image](https://user-images.githubusercontent.com/3768500/39230304-5069e5f4-4866-11e8-8527-914d7e21a0f0.png)
Good that the other stuff works :)
About the notifications: I'll see if I can do something about it.

**Comment by Fyro-Ing** [comment]
Use [this](https://github.com/RaulPPelaez/Naga_KeypadMapper) for key remapping.

**Comment by Ranyaws** [comment]
Hey, I'm on Linux Mint, have a Naga Epic Chroma, and would like the sidebuttons to work(E: be configurable, I mean). What do I have to do to help testing?

**Comment by DxCx** [comment]
i have the same mouse, looking at the posts im not really sure whats the current status?
is there a patch i can help testing? if so, how do i apply it (im using arch, installed openrazer from aur)

**Comment by z3ntu** [comment]
@DxCx Download the `openrazer-git` PKGBUILD from the AUR and replace the source line with `source=("$pkgbase::git+https://github.com/openrazer/openrazer.git#branch=feature_nagaepicchroma_0x003e")`

**Comment by DxCx** [comment]
Thank you! Will give it a try and report back

**Comment by DxCx** [comment]
so, i've used pacaur to replace my old openrazer-meta with openrazer-meta-git package.
thanks alot for that @z3ntu 
but polychromatic still doesnt see the device,
i've opened the log:
```
2018-07-20 09:30:21 | razer                          | INFO     | Initialising Daemon (v2.3.1). Pid: 1557
2018-07-20 09:30:21 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerAbyssus ---------------------------- (1532:0042)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerAbyssus1800 ------------------------ (1532:0020)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerAbyssusV2 -------------------------- (1532:005B)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerAnansi ----------------------------- (1532:010F)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChroma ------------------- (1532:0203)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaOverwatch ---------- (1532:0211)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaTournamentEdition -- (1532:0209)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaV2 ----------------- (1532:0221)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowStealth ------------------ (1532:011B)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowStealthEdition ----------- (1532:010E)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2012 ------------- (1532:010D)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2013 ------------- (1532:011A)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2016 ------------- (1532:0214)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXChroma ------------------ (1532:0216)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXTournamentEditionChroma - (1532:021A)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXUltimate ---------------- (1532:0217)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerBladeLate2016 ---------------------- (1532:0224)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerBladePro2017 ----------------------- (1532:0225)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerBladePro2017FullHD ----------------- (1532:022F)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerBladeProLate2016 ------------------- (1532:0210)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerBladeQHD --------------------------- (1532:020F)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealth ----------------------- (1532:0205)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthLate2016 --------------- (1532:0220)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthLate2017 --------------- (1532:0232)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthMid2017 ---------------- (1532:022D)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerChromaMugHolder -------------------- (1532:0F07)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerCore ------------------------------- (1532:0215)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerCynosaChroma ----------------------- (1532:022A)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdderChroma ------------------- (1532:0043)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdderElite -------------------- (1532:005C)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerDeathStalkerChroma ----------------- (1532:0204)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerDeathStalkerExpert ----------------- (1532:0202)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerDiamondbackChroma ------------------ (1532:004C)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerFirefly ---------------------------- (1532:0C00)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerImperator -------------------------- (1532:002F)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerKraken ----------------------------- (1532:0504)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerKrakenClassic ---------------------- (1532:0501)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerKrakenV2 --------------------------- (1532:0510)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerMamba2012Wired --------------------- (1532:0024)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerMamba2012Wireless ------------------ (1532:0025)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaWired ------------------- (1532:0044)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaWireless ---------------- (1532:0045)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerMambaTE ---------------------------- (1532:0046)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerNaga2014 --------------------------- (1532:0040)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerNagaChroma ------------------------- (1532:0053)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerNagaHex ---------------------------- (1532:0041)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerNagaHexRed ------------------------- (1532:0036)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerNagaHexV2 -------------------------- (1532:0050)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerNostromo --------------------------- (1532:0111)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerOrbweaver -------------------------- (1532:0113)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerOrbweaverChroma -------------------- (1532:0207)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerOrnata ----------------------------- (1532:021F)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerOrnataChroma ----------------------- (1532:021E)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerOrochi2011 ------------------------- (1532:0013)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerOrochi2013 ------------------------- (1532:0039)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerOrochiWired ------------------------ (1532:0048)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerOuroboros -------------------------- (1532:0032)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerTaipan ----------------------------- (1532:0034)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerTartarus --------------------------- (1532:0201)
2018-07-20 09:30:21 | razer                          | DEBUG    | Loaded device specification: RazerTartarusChroma --------------------- (1532:0208)
2018-07-20 09:30:21 | razer                          | DEBUG    | Adding razer.devices.getOffOnScreensaver method to DBus
2018-07-20 09:30:21 | razer                          | DEBUG    | Adding razer.devices.enableTurnOffOnScreensaver method to DBus
2018-07-20 09:30:21 | razer                          | DEBUG    | Adding razer.devices.getSyncEffects method to DBus
2018-07-20 09:30:21 | razer                          | DEBUG    | Adding razer.daemon.version method to DBus
2018-07-20 09:30:21 | razer                          | DEBUG    | Adding razer.daemon.stop method to DBus
2018-07-20 09:30:21 | razer                          | DEBUG    | Adding razer.devices.syncEffects method to DBus
2018-07-20 09:30:21 | razer                          | DEBUG    | Adding razer.devices.supportedDevices method to DBus
2018-07-20 09:30:21 | razer                          | DEBUG    | Adding razer.devices.getDevices method to DBus
2018-07-20 09:30:21 | razer                          | INFO     | Serving DBus
2018-07-20 09:30:23 | razer                          | DEBUG    | DBus called get_serial_list
2018-07-20 09:30:23 | razer                          | DEBUG    | DBus called get_serial_list
2018-07-20 09:30:42 | razer                          | DEBUG    | DBus called get_serial_list
2018-07-20 09:31:07 | razer                          | DEBUG    | DBus called get_serial_list
```

i still can't see my device in the list
how can i make sure the installed openrazer contains the support?
and if it does what should be my next steps?

Edit:
I've made sure again i've replacecd the correct line in PKGBUILD and it looks like i did,
however i cant see the new device class under
/usr/lib/python3.6/site-packages/openrazer_daemon/hardware/mouse.py
as it was added in the support branch:
https://github.com/openrazer/openrazer/compare/feature_nagaepicchroma_0x003e#diff-01d9a4553da1b05815c0b51d357ed0b0R870

so most likely something isn't installed correctly :\

**Comment by z3ntu** [comment]
@DxCx `pacman -Q openrazer-meta openrazer-driver-dkms openrazer-daemon python-openrazer` ?

**Comment by DxCx** [comment]
```
pacman -Q openrazer-meta openrazer-driver-dkms openrazer-daemon python-openrazer
openrazer-meta-git 2.3.0.r14.g025f76d-1
openrazer-driver-dkms 2.3.1-2
openrazer-daemon 2.3.1-2
python-openrazer 2.3.1-2
```

Thanks!!

**Comment by z3ntu** [comment]
You also have to install the other -git packages that you built with the modified PKGBUILD - the metapackage itself contains nothing except the dependencies to the other packages.

**Comment by DxCx** [comment]
im not sure how to achieve that
tried a complete reinstall of everything (using pacman -Rdd first) but that didnt help
i get the same exact packages afterwards
also, coulldn't find -git version pacakges using pacaur -Ss command

**Comment by z3ntu** [comment]
Git clone https://aur.archlinux.org/openrazer-git.git
Edit the pkgbuild
Run makepkg -sric

**Comment by DxCx** [comment]
thanks alot @z3ntu 
now i have:
```
openrazer-meta-git 2.3.0.r14.g025f76d-1
openrazer-driver-dkms-git 2.3.0.r14.g025f76d-1
openrazer-daemon-git 2.3.0.r14.g025f76d-1
python-openrazer-git 2.3.0.r14.g025f76d-1
```

**Comment by DxCx** [comment]
after a reboot, i can see in the logs:

```
2018-07-20 14:15:52 | razer                          | DEBUG    | Loaded device specification: RazerNagaEpicChromaWired ---------------- (1532:003E)
2018-07-20 14:15:52 | razer                          | DEBUG    | Loaded device specification: RazerNagaHex ---------------------------- (1532:0041)
2018-07-20 14:15:52 | razer                          | DEBUG    | Loaded device specification: RazerNagaHexRed ------------------------- (1532:0036)
2018-07-20 14:15:52 | razer                          | DEBUG    | Loaded device specification: RazerNagaHexV2 -------------------------- (1532:0050)
2018-07-20 14:15:52 | razer                          | DEBUG    | Loaded device specification: RazerNostromo --------------------------- (1532:0111)
2018-07-20 14:15:52 | razer                          | DEBUG    | Loaded device specification: RazerOrbweaver -------------------------- (1532:0113)
2018-07-20 14:15:52 | razer                          | DEBUG    | Loaded device specification: RazerOrbweaverChroma -------------------- (1532:0207)
2018-07-20 14:15:52 | razer                          | DEBUG    | Loaded device specification: RazerOrnata ----------------------------- (1532:021F)
2018-07-20 14:15:52 | razer                          | DEBUG    | Loaded device specification: RazerOrnataChroma ----------------------- (1532:021E)
2018-07-20 14:15:52 | razer                          | DEBUG    | Loaded device specification: RazerOrochi2011 ------------------------- (1532:0013)
2018-07-20 14:15:52 | razer                          | DEBUG    | Loaded device specification: RazerOrochi2013 ------------------------- (1532:0039)
2018-07-20 14:15:52 | razer                          | DEBUG    | Loaded device specification: RazerOrochiWired ------------------------ (1532:0048)
2018-07-20 14:15:52 | razer                          | DEBUG    | Loaded device specification: RazerOuroboros -------------------------- (1532:0032)
2018-07-20 14:15:52 | razer                          | DEBUG    | Loaded device specification: RazerTaipan ----------------------------- (1532:0034)
2018-07-20 14:15:52 | razer                          | DEBUG    | Loaded device specification: RazerTartarus --------------------------- (1532:0201)
2018-07-20 14:15:52 | razer                          | DEBUG    | Loaded device specification: RazerTartarusChroma --------------------- (1532:0208)
2018-07-20 14:15:52 | razer                          | DEBUG    | Adding razer.devices.getDevices method to DBus
2018-07-20 14:15:52 | razer                          | DEBUG    | Adding razer.devices.getSyncEffects method to DBus
2018-07-20 14:15:52 | razer                          | DEBUG    | Adding razer.devices.getOffOnScreensaver method to DBus
2018-07-20 14:15:52 | razer                          | DEBUG    | Adding razer.devices.supportedDevices method to DBus
2018-07-20 14:15:52 | razer                          | DEBUG    | Adding razer.daemon.version method to DBus
2018-07-20 14:15:52 | razer                          | DEBUG    | Adding razer.daemon.stop method to DBus
2018-07-20 14:15:52 | razer                          | DEBUG    | Adding razer.devices.enableTurnOffOnScreensaver method to DBus
2018-07-20 14:15:52 | razer                          | DEBUG    | Adding razer.devices.syncEffects method to DBus
2018-07-20 14:15:52 | razer                          | INFO     | Serving DBus
2018-07-20 14:15:53 | razer                          | DEBUG    | DBus called get_serial_list
2018-07-20 14:15:59 | razer                          | DEBUG    | DBus called get_serial_list
2018-07-20 14:16:32 | razer                          | DEBUG    | Device event [unbind]: /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/0003:1532:003E.0002
2018-07-20 14:16:32 | razer                          | DEBUG    | Device event [remove]: /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/0003:1532:003E.0002
2018-07-20 14:16:32 | razer                          | DEBUG    | Device event [unbind]: /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.1/0003:1532:003E.0003
2018-07-20 14:16:32 | razer                          | DEBUG    | Device event [remove]: /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.1/0003:1532:003E.0003
2018-07-20 14:16:32 | razer                          | DEBUG    | Device event [unbind]: /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.2/0003:1532:003E.0004
2018-07-20 14:16:32 | razer                          | DEBUG    | Device event [remove]: /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.2/0003:1532:003E.0004
2018-07-20 14:16:33 | razer                          | DEBUG    | Device event [add]: /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.1/0003:1532:003E.0006
2018-07-20 14:16:33 | razer                          | DEBUG    | Device event [add]: /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/0003:1532:003E.0005
2018-07-20 14:16:33 | razer                          | DEBUG    | Device event [add]: /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.2/0003:1532:003E.0007
2018-07-20 14:16:34 | razer                          | DEBUG    | Device event [bind]: /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/0003:1532:003E.0005
2018-07-20 14:16:34 | razer                          | DEBUG    | Device event [bind]: /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.1/0003:1532:003E.0006
2018-07-20 14:16:34 | razer                          | DEBUG    | Device event [bind]: /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.2/0003:1532:003E.0007
2018-07-20 14:16:45 | razer                          | DEBUG    | DBus called get_serial_list
2018-07-20 14:16:49 | razer                          | DEBUG    | DBus called get_serial_list
2018-07-20 14:16:51 | razer                          | DEBUG    | DBus called get_serial_list
```

but still polychromatic doesn't detect device
do i need to do something more?

**Comment by z3ntu** [comment]
Does anything happen with these commands?
```
sudo dkms install openrazer-driver/2.3.0
sudo modprobe razercore
```

**Comment by DxCx** [comment]
ok so aprentaly i didnt had the linux headers so dkms wasn't really built, hence, driver was not used.
dkms build step was returning success, altough it wasn't really installed.

now it does, thanks alot @z3ntu !

So, for future users, to sum it up, to make it work i've:
1. Make sure kernel headers are avilable (mine was linux414-headers).
2. Git clone https://aur.archlinux.org/openrazer-git.git
3. edit PKGBUILD file, replacing `source=` line with
`source=("$pkgbase::git+https://github.com/openrazer/openrazer.git#branch=feature_nagaepicchroma_0x003e")`
4. run makepkg -sric
5. reboot

**Comment by DxCx** [comment]
so wired mode looks ok,
polychormatic works, there are some wired stuff but i belive those are UI issues/bugs since values updated but not pulled correctly back to the user.
razercommander showes the values stored by polychormatic just ok.

however, when switching to "dock mode", it doesn't recorgnaize the device as well,
looks like USB PID has changed:
```Bus 001 Device 008: ID 1532:003f Razer USA, Ltd```

**Comment by z3ntu** [comment]
Yeah dock mode is not supported yet.

**Comment by DxCx** [comment]
alright, when it does i dont mind help testing that as well =)
btw, firmware updates are supported by openrazer? or to get firmware updates i'll have to connect the mouse to a windows station?

**Comment by z3ntu** [comment]
No firmware updates, sorry.

**Comment by mentos1386** [comment]
@z3ntu any progress towards dock mode support? Is there anyway I can help with this?

**Comment by hXtreme** [comment]
Is the wired mode supported in the latest release on PPA? If so, the mouse isn't recognized for me.

**Comment by lavabrothers** [comment]
Sorry to Necro this issue. Has there been any developments as of late? The repository given to fix the issue no longer exists and the main branch doesn't support even the wired version. If any pictures or information is needed from me I'm happy to provide

**Comment by z3ntu** [comment]
@lavabrothers I've rebased the old branch, please test #1695 . Details are written there.

**Comment by ChaoticAce** [comment]
Can also confirm that this branch works for both wired and wireless mode. In order to get it running I had to remove the following packages:
```
razergenie-git
polychromatic-git
openrazer-meta-git
openrazer-driver-dkms-git 
openrazer-daemon-git 
python-openrazer-git 
```

Once removed I reinstalled the following packages with a modified PKGBUILD file:
```
openrazer-meta-git
openrazer-driver-dkms-git 
openrazer-daemon-git 
python-openrazer-git 
```

`PKGBUILD` File modifications: 
```
# source=("git+https://github.com/openrazer/openrazer.git")
source=("git+https://github.com/openrazer/openrazer.git#branch=feature_nagaepicchroma_0x003e")
```

Then I reinstalled the packages below and rebooted my machine:
```
razergenie-git
polychromatic-git
```
Both `polychromatic` and `razergenie` recognized my mouse after a reboot. I was able to modify Mouse: Brightness, Pollrate, sleep mode, lower power mode and DPI. Scroll Wheel: Brightness, Spectrum/static. Backlight, and all color zones. Glad to finally be able to modify my mouse. I haven't tried keymapping yet
